title: Jinyu Xie
description: Jinyu Xie - Senior Research Engineer at Google DeepMind Robotics
url: "https://jxx123.github.io"
baseurl: ""

# Build
markdown: kramdown
kramdown:
  input: GFM

# Exclude from build
exclude:
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - "*.gemspec"
  - rollup.config.js
  - package*.json
  - docs
  - tools
